client client {
	ipaddr = $ENV{CLIENT_ADDRESS}
	secret = $ENV{CLIENT_SECRET}
	
	# FIX: Update this from 'no' to 'yes' / 'true' to pass BlastRADIUS mitigations
	require_message_authenticator = yes
	
	# Optional safety: Allows handling packets without proxy states gracefully
	limit_proxy_state = yes
}
